services:
  iris:
    build:
      args:
        IRIS_IMAGE: ${IRIS_IMAGE_ARM}
        IRIS_TAG: ${IRIS_TAG}
      context: .
      dockerfile: ./src-iris/Dockerfile
      secrets:
        - iris_pw
    environment:
      - ISC_DATA_DIRECTORY=/iris-shared/external
      - ISC_CPF_MERGE_FILE=/iris-shared/cpf/cpfmerge.cpf
    volumes:
      - ./volumes/iris:/iris-shared
    env_file: .env
    ports:
      - "51972:1972"
      - "52773:52773"
  streamlit:
    build:
      context: ./src-streamlit
    secrets:
      - iris_pw
    ports:
      - "${STREAMLIT_PORT}:8501"
    links:
      - iris
secrets:
  iris_pw:
    file: "./src-iris/irispw.txt"
