Class Demo.Operations.LlmLocal.Messages.ToolResultRequest Extends (%Persistent, Ens.Request)
{

Property Arguments As %String(MAXLEN = "");

Storage Default
{
<Data name="ToolResultRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Arguments</Value>
</Value>
</Data>
<DataLocation>^Demo.OperaF64A.ToolResultR867ED</DataLocation>
<DefaultData>ToolResultRequestDefaultData</DefaultData>
<IdLocation>^Demo.OperaF64A.ToolResultR867ED</IdLocation>
<IndexLocation>^Demo.OperaF64A.ToolResultR867EI</IndexLocation>
<StreamLocation>^Demo.OperaF64A.ToolResultR867ES</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
